### ISSUE TITLE
User Account Details Component

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#146]
- [ ] Create a Component which reports high-level metadata about a user found in their User record.
- [ ] This Component should look good as a full page Component.
- [ ] It should also look good if included as a single element on a busy page like on #139 
- [ ] Add this Component to #139 
- [ ] If the user has a subscription (#147) then show the details here
- [ ] Add a button to cancel your subscription.  Behavior already described in #147

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

This involves also finishing the AppWrite integration, as well as making decisions about what data to show, and where that data will be stored. AppWrite only stores email, status (if they are logged in at the moment), registration (timestamp of when they registered), confirm (if they've confirmed there account through the email provided), and name (which we currently do not have a way for them to provide).

As for subscription and any related data, this would need to be stored in a users table of some form that FastSPA can access; doing this through AppWrite seems logical, however this would need to be created and then populated.

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

This involves also finishing the AppWrite integration, as well as making decisions about what data to show, and where that data will be stored. AppWrite only stores email, status (if they are logged in at the moment), registration (timestamp of when they registered), confirm (if they've confirmed there account through the email provided), and name (which we currently do not have a way for them to provide).

As for subscription and any related data, this would need to be stored in a users table of some form that FastSPA can access; doing this through AppWrite seems logical, however this would need to be created and then populated.

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

If the subscription information is coming from DynamoDB, then this table would either need to be updated to store their AppWrite userId or we would need to create a map table in AppWrite that contains this id, as well as their DynamoDB id in order to specify that they are related.

Either way, this task will require a bit more work in order to get to it.
