### ISSUE TITLE
Buy a subscription

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#147]
# List Subscriptions

- [ ] If the user is a FREE member, then alter the display of #146 to include this message:

> Unlock features and raise limits with a paid account.  Click here to upgrade.

- [ ] Click brings the user to a NEW page with a list of PLANS taken from the Stripe API.

https://stripe.com/docs/api/plans/object

```
{
  "id": "sku_9",
  "object": "plan",
  "active": true,
  "aggregate_usage": null,
  "amount": 25600,
  "amount_decimal": "25600",
  "billing_scheme": "per_unit",
  "created": 1515965039,
  "currency": "usd",
  "interval": "month",
  "interval_count": 1,
  "livemode": false,
  "metadata": {},
  "nickname": null,
  "product": "prod_C8a7Argq1QK6t4",
  "tiers": null,
  "tiers_mode": null,
  "transform_usage": null,
  "trial_period_days": null,
  "usage_type": "licensed"
}
```

- [ ] Show a list ordered by price.

# Buy a Subscription Details Page

- [ ] Check Appwrite (see #145).  If the user already has a Subscription *To Forager*.  If so, present the option to cancel it.
- [ ] Cancel should have "are you sure" modal.  If no, submit SNS event.  If yes, submit SNS event AND use Stripe API to cancel.
- [ ] Once a user clicks the plan they want, take them IMMEDIATELY to a details page with lots of information on the plan, especially anything that couldn't fit in the list screen.

- [ ] Use a STANDARD non-custom template to collect Billing information, shipping information (checkbox for same), phone, name, etc.  Match our fields to those that are in Stripe's [Customer Object](https://stripe.com/docs/api/customers)

- [ ] Use the STRIPE provided custom components for taking the credit card information.

- [ ] Add a checkout button

- [ ] Checkout button is disabled unless required fields are filled

# Click checkout

- [ ] Show wait screen

- [ ] Create a Stripe customer

- [ ] Create a Stripe subscription based on the customer and Stripe Plan

- [ ] Submit to Stripe

- [ ] On failure, Modal for error and return to page with first error field in focus and highlighted

- [ ] Show some visual progress (even if the non-developer doesn't know the meaning) so that we can visually see which step above is taking the time.

# On Success

- [ ] Add subscription information to the User's DynamoDB Record as described in #145 

- [ ] Publish an SNS message
